{{- if or .Values.autoscaler.enabled .Values.externalDns.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "binarylane-controller.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "binarylane-controller.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.autoscaler.enabled }}
    - port: {{ .Values.service.autoscalerPort }}
      targetPort: cluster-autoscaler
      protocol: TCP
      name: cluster-autoscaler
    {{- end }}
    {{- if .Values.externalDns.enabled }}
    - port: {{ .Values.service.externalDnsPort }}
      targetPort: external-dns
      protocol: TCP
      name: external-dns
    {{- end }}
  selector:
    {{- include "binarylane-controller.selectorLabels" . | nindent 4 }}
{{- end }}
